// Exact source text keys prevent stale translations after a graph edit.
export const KNOWLEDGE_EN: Record<string, string> = {
  "未明确目标": "No target selected",
  "读取告警以定位候选，必要时澄清。": "Read alerts to identify candidates; clarify when needed.",
  "不要任意选择商品写入。": "Do not choose an arbitrary write target.",
  "目标已明确": "Target is explicit",
  "读取目标完整记录并确认对象类型。": "Read the full target record and confirm its type.",
  "用户提供id不是provenance。": "A user-supplied ID is not provenance.",
  "已确定单一目标": "One target has been selected",
  "读取完整商品或规格。": "Read the full listing or variant.",
  "告警读取未建立上游seen_listings。": "Alerts do not establish seen_listings provenance.",
  "完整告警为空且任务只要求检查": "Complete alerts are empty for a check-only task",
  "报告范围内未发现告警。": "Report no alerts within the observed scope.",
  "空告警不证明所有业务健康。": "Empty alerts do not prove overall business health.",
  "目标有效且可用于本任务": "Target is valid for this task",
  "刷新当前队列快照。": "Refresh the current pending queue snapshot.",
  "历史seen_changes不是当前队列。": "Historical seen_changes is not the current queue.",
  "目标不存在、含糊或分类冲突": "Target is missing, ambiguous or contradictory",
  "请求必要的目标／规格信息。": "Ask for the required target or variant.",
  "不猜测其他目标。": "Do not guess another target.",
  "收到标注覆盖情况的队列观察": "A queue observation includes coverage metadata",
  "检查完整性、当前性与同目标冲突。": "Check completeness, freshness and same-target conflicts.",
  "部分响应不能证明没有待处理变更。": "A partial response cannot establish absence.",
  "同目标存在待处理库存变更": "A pending inventory change affects the same target",
  "复核已有变更，不新建重复方案。": "Review the existing change instead of duplicating it.",
  "暂存数量不等于可用库存。": "Staged units are not available stock.",
  "输入有效且完整队列中无冲突": "Inputs are valid and the complete queue has no conflict",
  "调用确定性计算工具。": "Use the deterministic calculation tool.",
  "不让LLM自报库存和销量。": "The model cannot supply its own stock or sales.",
  "数据未知、冲突或无法补读": "Data is unknown, conflicting or cannot be refreshed",
  "说明缺少什么及其影响。": "Explain the missing data and its impact.",
  "不能把None当0。": "None is not zero.",
  "方案为正且在当前限制内": "The positive plan is within the current limits",
  "核对目标、Q和版本后暂存。": "Check the target, quantity and revision before staging.",
  "不修改公式、不规避上限。": "Do not change the formula or bypass limits.",
  "计算结果不需要正向自动补货": "The calculation does not support positive restocking",
  "提供不操作的计算依据。": "Explain the calculation supporting no action.",
  "不创建零数量变更。": "Do not create a zero-quantity change.",
  "缺数据或方案超过规则范围": "Data is missing or the plan exceeds policy",
  "请求处理输入或人工决策。": "Request corrected input or operator intervention.",
  "不得截断或拆单绕过上限。": "Do not clamp or split to bypass limits.",
  "暂存成功且预览已渲染": "Staging succeeded and the preview was rendered",
  "说明尚未生效，等待宿主入口。": "State that the change is pending host approval.",
  "自动预览无需重复展示，不能自动批准。": "Do not duplicate the automatic preview or grant approval.",
  "方案过期且重查预算尚在": "The plan expired and recovery budget remains",
  "废弃旧方案并重新读取。": "Invalidate the old plan and refresh the listing.",
  "重查不是重放写入。": "Refreshing evidence is not replaying a write.",
  "原子检查发现同目标冲突": "An atomic check found a same-target conflict",
  "复核已有变更并结束本轮。": "Review the existing change and end the round.",
  "不重建新id绕过冲突。": "A new ID cannot bypass a conflict.",
  "可信宿主应用成功事件": "A trusted host event confirms application",
  "读取当前业务状态并核对执行回执。": "Read current state and verify the execution receipt.",
  "不要再次调用apply。": "Do not apply the change again.",
  "可信宿主丢弃事件": "A trusted host event confirms discard",
  "记录拒绝和结束原因。": "Record the refusal and reason for stopping.",
  "不生成相同新单绕过拒绝。": "Do not recreate the same change to bypass refusal.",
  "真实应用结果不确定": "The application outcome is uncertain",
  "仅查询或请求人工核对。": "Use reads or ask for operator reconciliation.",
  "超时不证明无副作用。": "A timeout does not prove no effect occurred.",
  "授权效果已经验证": "The authorized effect has been verified",
  "报告可核查的完成结果。": "Report the result with verifiable evidence.",
  "不能只凭模型自报成功。": "A model success claim is insufficient.",
  "结果不一致或仍未知": "The result differs or remains unknown",
  "记录差异和未验证状态。": "Record the discrepancy and unverified state.",
  "不自动反向补货。": "Do not automatically create an inverse restock.",
  "已取得可判定的应用结果": "An authoritative application result is available",
  "重新读取并核查效果。": "Read again and verify the effect.",
  "不重新发起副作用。": "Do not initiate the side effect again."
};
